### ISSUE TITLE
Remove cap on NearestNeighbors.jl version

### ISSUE THREAD

**Issue by ablaom** [OutlierDetectionJL/OutlierDetectionNeighbors.jl#5]
Currently version is capped: `NearestNeighbors = "<0.4.14"` but 0.4.16 is the latest. Is there a reason for this?

**Comment by davnn** [comment]
Yes there was a reason, but I can now update to ``<0.4.14,>0.4.15``.

https://github.com/KristofferC/NearestNeighbors.jl/issues/173

**Comment by davnn** [comment]
Landed in v0.1.5 https://github.com/OutlierDetectionJL/OutlierDetectionNeighbors.jl/commit/256ebe6a9a64c189b11c30a3ef6bceb3c2e29b61

**Comment by ablaom** [comment]
Thanks!
